NewsPaperKAI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('pages/', include('django.contrib.flatpages.urls')),
    # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
    # подключались к главному приложению с префиксом products/.
    path('', include('news.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
]

news/urls.py
from django.urls import path
from .views import PostList, PostDetail, SearchNews, PostCreate, PostUpdate, PostDelete, ProfileUserUpdate

urlpatterns = [
    path('news/', PostList.as_view()),
    path('news/<int:pk>', PostDetail.as_view()),
    path('news/search', SearchNews.as_view(), name='search_news'),
    path('news/create/', PostCreate.as_view(), name='post_create'),
    path('news/<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
    path('news/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('profile/<int:pk>/update/', ProfileUserUpdate.as_view(), name='profile_user_update'),
]

news/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.db.models import Sum


class Author(models.Model):
    user_author = models.OneToOneField(User, on_delete=models.CASCADE)
    rating_author = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user_author}'

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.user_author.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.rating_author = pRat*3 + cRat
        self.save()



class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return f'{self.name}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICE = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )
    category_type = models.CharField(max_length=2, choices=CATEGORY_CHOICE, default=ARTICLE)
    time_create = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=256)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return f'{self.text[0:125]} ... rating: {str(self.rating)}'

    def __str__(self):
        return f'{self.text[:100]}...'

    def get_absolute_url(self):
        return f'/news/{self.pk}'


class PostCategory(models.Model):
    post_through = models.ForeignKey(Post, on_delete=models.CASCADE)
    category_through = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    time_create = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        try:
            return self.comment_post.author.user_author.username
        except:
            return self.comment_user.username

news/forms.py
from django.forms import ModelForm, BooleanField  # Импортируем true-false поле
from django import forms
from .models import Post, User


# Создаём модельную форму
class PostForm(ModelForm):
    # check_box = BooleanField(label='Ало, Галочка!')  # добавляем галочку, или же true-false поле
    # в класс мета, как обычно, надо написать модель, по которой будет строится форма и нужные нам поля. Мы уже делали что-то похожее с фильтрами.
    class Meta:
        model = Post
        fields = [
          'author',
          'category_type',
          'title',
          'text'
          ]

        widgets = {
          'authorType' : forms.TextInput(attrs={'class': 'form-control pure-input-1-2'}),
          'category' : forms.Select(attrs={'class': 'form-control pure-input-1-2'}),
          'title' : forms.TextInput(attrs={'class': 'form-control pure-input-1-2',   'placeholder': 'Post Title'}),
          'text': forms.Textarea(attrs={'class': 'form-control pure-input-1-2'})
        }
        labels = {
                    "author": "Author",
                    "category_ype": "Category",
                    "title": "Title",
                    "text": "Text",
                }


class ProfileUserForm(forms.ModelForm):
    class Meta:
        model = User
        # fields = '__all__'
        fields = [
            'first_name',
            'last_name',
            'email',
            'username',
            # 'password',

        ]

news/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.forms import forms
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView, UpdateView, CreateView,  DeleteView, TemplateView

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView

# импортируем недавно написанный фильтр
from .filters import PostFilter, F, C, D
from .forms import PostForm, ProfileUserForm  # импортируем нашу форму
from .models import Post, Comment, Category, Author, User


class PostList(ListView):
    model = Post
    ordering = 'time_create'
    template_name = 'news_list.html'
    context_object_name = 'news_list'
    queryset = Post.objects.order_by('-time_create')
    form_class = PostForm
    paginate_by = 10 # вот так мы можем указать количество записей на странице

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        context['categories'] = Category.objects.all()
        context['form'] = PostForm
        return context


class PostDetail(DetailView):
    # Модель всё та же, но мы хотим получать информацию по отдельной новости
    model = Post
    # Используем другой шаблон — news_one.html
    template_name = 'news_one.html'
    # Название объекта, в котором будет выбранная пользователем новость
    context_object_name = 'news_one'


class ProfileUserUpdate(LoginRequiredMixin, UpdateView):
    form_class = ProfileUserForm
    model = User
    template_name = 'profile_edit.html'
    success_url = '/news/'


class HomePageView(View):
    template_name = "index.html"


class SearchNews(ListView):
    template_name = 'search.html'
    context_object_name = 'search_news'
    queryset = Post.objects.all()
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())  # вписываем наш фильтр в контекст
        context['categories'] = Category.objects.all()
        context['form'] = PostForm
        return context


class PostCreate(PermissionRequiredMixin, CreateView):
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'
    success_url = '/news/'

    permission_required = ('news.add_post')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_author = Author.objects.get(authorUsername=self.request.user)
        # print(self.request.user)
        self.object.save()
        return super().form_valid(form)


class PostUpdate(PermissionRequiredMixin, UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'
    success_url = '/news/'

    permission_required = ('news.change_post')

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class PostDelete(PermissionRequiredMixin, DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = "/news/"

    permission_required = ('news.delete_post')

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)
# Create your views here.

news/templates/news/default.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Итоговый проект по Django (Начало)</title>
        <!-- Favicon-->
        <!-- Core theme CSS (includes Bootstrap)-->
        {% load static %}
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
   <div class="container">
       <a class="navbar-brand" href="#">ЗНАКОМСТВО с DJANGO</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse"
               data-target="#navbarResponsive"
               aria-controls="navbarResponsive" aria-expanded="false"
               aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarResponsive">
           <ul class="navbar-nav ml-auto">
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="/news/">ВСЕ НОВОСТИ</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="/news/search">ПОИСК</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="/news/create">Создать новость (статью)</a>
               <li class="nav-item">
                   <a class="nav-link" href="/sign/signup">Регистрация пользователя</a>
               <li class="nav-item">
                   <a class="nav-link" href="/sign/login">ВОЙТИ</a>
               <li class="nav-item">
                   <a class="nav-link" href="/sign/logout">ВЫЙТИ</a>
               <li class="nav-item">
                   <a class="nav-link" href="/admin">Панель админа</a>
               </li>
           </ul>
       </div>
   </div>
</nav>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-conter">
                    {% block title %}
                    {% endblock title %}
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </body>
</html>

news/templates/news/news_list.html
{% extends 'default.html' %}

{% load custom_filters %}

{% block title %}
<p>&nbsp;</p>
<h3><span style="color: #ff0000;"><strong>ВСЕ НОВОСТИ</strong></span>
<p>&nbsp;</p></h3>
{% endblock title %}

{% block content %}
<table class="table" style="width: auto; margin: auto; text-align: center;">
    <thead class="">
    <tr>
        <th>ЗАГОЛОВОК</th>
        <th>ДАТА ПУБЛИКАЦИИ</th>
        <th>ТЕКСТ ПОСТА</th>
        <th>РЕЙТИНГ ПОСТА</th>
        <th>АВТОР ПОСТА</th>
        <th>РЕЙТИНГ АВТОРА</th>
        <th>ТИП</th>
    </tr>
    </thead>
    <tbody>
    {% if news_list %}
    {% for p in news_list %}
    <tr>
        <td><a href="{{ p.get_absolute_url }}"> {{ p.title|censor }} </a></td>
        <td>{{ p.time_create|date:'d F Y' }}</td>
        <td>{{ p.text|truncatechars:50|censor }}</td>
        <td><b>{{ p.rating }}</b></td>
        <td>{{ p.author.user_author}}</td>
        <td> {{ p.author.rating_author }}</td>
        <td> {{ p.category_type }}</td>
    </tr>
    {% endfor %}
    {% endif %}
    <tbody>

</table>

 {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
<p>&nbsp;</p></h3>

{% endblock content %}

news/templates/news/news_one.html
{% extends 'default.html' %}

{% load custom_filters %}

{% block content %}
<p><h3>{{ news_one.title|censor }}</h3></p>
<p>{{ news_one.text|censor }}</p>
<p>Дата публикации: {{ news_one.time_create|date:"d.m.Y" }}</p>
<p>Автор: {{ news_one.author }}</p>
<p>Рейтинг: {{ news_one.rating }}</p>

<button class="pure-button button-error">
    <i class="bi bi-trash"></i>
    <a href="{% url 'post_update' news_one.id %}"><u> Редактировать </u></a></button>

<button class="pure-button button-error">
    <i class="bi bi-trash"></i>
    <a href="{% url 'post_delete' news_one.id %}"><u> Удалить </u></a></button>



{% endblock content %}

news/templates/news/post_delete.html
{% extends 'default.html' %}

{% block title %}
<h1><strong><span style="color: #ff0000;">Вы действительно хотите удалить данный пост?</span><br /></strong></h1>
{% endblock title %}


{% block content %}

<section class="post">
  <header class="post-header">
      <h2 class="post-title">{{post.title}}</h2>
    </a>
    <p class="post-meta"><strong>Автор статьи:</strong> {{post.author}}
      </a>
      <p>
      <strong>Дата создания новости(статьи):</strong>
      <i>{{ post.time_create|date:'d M Y H:i' }}</i>
    <p>
      <p class="post-category post-category-{{post.category_type}}">
        <strong>Категория поста:</strong> {{post.get_category_type_display }} </p>
      </p>
    </p>
  </header>
  <div class="post-description">
    <p>{{ post.text|truncatewords:25 }}</p>
    <p><em>Рейтинг новости(статьи): {{post.rating}} </em></p>
  </div>
</section>


<form method="POST">
  {% csrf_token %}
  <button class="pure-button button-error">
    <i class="bi bi-trash"></i>
    Удалить</button>
</form>
{% endblock content %}

news/templates/news/post_edit.html
{% extends 'default.html' %}

{% block title %}
<p>&nbsp;</p>
<h3><span style="color: #ff0000;"><strong>СОЗДАНИЕ НОВОСТИ(СТАТЬИ):</strong></span>
<p>&nbsp;</p></h3>
{% endblock title %}

{% block content %}
<h3>Новый пост (новость, статья)</h3>
<form method="POST">
  {% csrf_token %}
  {{ form }}
  <br>
  <br>
  <button class="pure-button button-success">
    <i class="bi bi-check2-square"></i>
    Создать новость(статью):</button>

</form>
{% endblock content %}

news/templates/news/profile_edit.html
{% extends 'default.html' %}

{% block title %}
<h1><strong><span style="color: #ff0000;">Редактирование профиля</span><br /></strong></h1>
{% endblock title %}

{% block content %}
{% if request.user.id != profile.id %}
<h1>Редактирование профиля</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% endif %}
{% endblock content %}

news/templates/news/search.html
{% extends 'default.html' %}

{% load custom_filters %}

{% block title %}
<p>&nbsp;</p>
<h3><span style="color: #ff0000;"><strong>ПОИСК НОВОСТЕЙ(СТАТЕЙ):</strong></span>
<p>&nbsp;</p></h3>
{% endblock title %}

{% block content %}
<!-- Перед таблицей добавим форму для поиска -->
<form class="pure-form" method="GET">
  <fieldset>

    {{ filter.form }}
    <!-- Форму от фильтров за нас сделает django. А вот кнопку, увы придётся делать самому -->
  </fieldset>

  <button class="pure-button button-secondary">
    Найти
  </button>
</form>
<!--  loop -->
<p>
  {{filter.category_type}}
</p>
<p>
  {{filter.qs.category_type }}
</p>
{% if filter == null %}
<h3>
  no posts
</h3>
{%else%}
<h3 class="content-subhead">
  Найдено новостей(статей):
  <span>{{ filter.qs|length }}</span>
</h3>
{% for n in filter.qs %}
<!--  A single blog post -->
<section class="post">
  <a href="./{{n.id}}">
      <h1class="post-title">{{n.title|censor}}</h1>
    </a>
    <p class="post-meta">Автор:
      <a class="post-author" href="#">
        {{ n.author }}
      </a>
      <p>Дата публикации:
      <i>{{ n.time_create|date:'d M Y H:i' }}</i></p>
      <a class="post-category post-category-{{n.categoryType}}" href="#">
        Категория: {{n.get_category_type_display }}
      </a>
    </p>
  </header>
  <div class="post-description">
    <p>{{ n.text|censor | truncatewords:25 }}</p>
    <p><em>Рейтинг: {{n.rating}} </em></p>
  </div>
</section>
<hr />
{%endfor%}
{%endif%}

{% endblock content %}